Repository aritra-tech/Notify, pull requests merged in 2023-09, with the labels that each got.

#66 Implemented auto-update on new changes to note
  app/src/main/java/com/aritra/notify/components/topbar/AddNoteTopBar.kt
Labels: enhancement, good first issue, priority-medium

#71 Implement backup and restore with csv
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aritra/notify/components/note/GridNoteCard.kt
  app/src/main/java/com/aritra/notify/components/note/NoteCard.kt
  app/src/main/java/com/aritra/notify/components/topbar/AddNoteTopBar.kt
  app/src/main/java/com/aritra/notify/components/topbar/EditNoteTopBar.kt
  app/src/main/java/com/aritra/notify/data/converters/DateTypeConverter.kt
  app/src/main/java/com/aritra/notify/data/converters/UriConverter.kt
  app/src/main/java/com/aritra/notify/data/dao/NoteDao.kt
  app/src/main/java/com/aritra/notify/data/db/NoteDatabase.kt
  app/src/main/java/com/aritra/notify/data/models/Note.kt
  app/src/main/java/com/aritra/notify/data/repository/BackupRepository.kt
  app/src/main/java/com/aritra/notify/data/repository/NoteRepository.kt
  app/src/main/java/com/aritra/notify/domain/usecase/SaveSelectedImageUseCase.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addNoteScreen/AddNoteViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addNoteScreen/AddNotesScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/editNoteScreen/EditNotesScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/editNoteScreen/EditScreenViewModel.kt
  app/src/main/java/com/aritra/notify/utils/Const.kt
  app/src/main/java/com/aritra/notify/utils/Context.kt
  app/src/main/java/com/aritra/notify/utils/CsvIo.kt
  app/src/main/java/com/aritra/notify/utils/DateTypeConverter.kt
  app/src/main/java/com/aritra/notify/utils/Uri.kt
  app/src/main/res/xml/file_provider_paths.xml
Labels: enhancement, priority-medium, features

#93 Subject: Merge Request for "Text to String Resources" Feature in Notify App
  app/src/main/java/com/aritra/notify/components/actions/BackPressHandler.kt
  app/src/main/java/com/aritra/notify/components/biometric/AppBioMetricManager.kt
  app/src/main/res/values/strings.xml
Labels: good first issue, codebase-improvement
