Repository aritra-tech/Notify, pull requests merged in 2023-10, with the labels that each got.

#96 Fixed : Note click effect
  app/src/main/java/com/aritra/notify/components/note/NoteCard.kt
Labels: improvement, ui-fixes, hacktoberfest-accepted

#101 Fixed : edit note issue
  app/src/main/java/com/aritra/notify/components/note/GridNoteCard.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/editNoteScreen/EditNotesScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
Labels: bug, good first issue, hacktoberfest-accepted

#104 Optimized code by combining screens
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyScreens.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addNoteScreen/AddNoteViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/editNoteScreen/EditNotesScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/editNoteScreen/EditScreenViewModel.kt
Labels: good first issue, codebase-improvement, hacktoberfest-accepted

#108 Single tap top
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
Labels: good first issue, features, hacktoberfest-accepted

#114 Add ktlint
  .editorconfig
  .github/workflows/ci_build.yml
  app/build.gradle.kts
  app/src/androidTest/java/com/aritra/notify/ExampleInstrumentedTest.kt
  app/src/main/java/com/aritra/notify/NotifyApplication.kt
  app/src/main/java/com/aritra/notify/components/actions/BackPressHandler.kt
  app/src/main/java/com/aritra/notify/components/actions/BottomSheetOptions.kt
  app/src/main/java/com/aritra/notify/components/actions/LayoutToggleButton.kt
  app/src/main/java/com/aritra/notify/components/actions/SettingsComponent.kt
  app/src/main/java/com/aritra/notify/components/actions/SettingsSwitchCard.kt
  app/src/main/java/com/aritra/notify/components/actions/ShareOption.kt
  app/src/main/java/com/aritra/notify/components/actions/SpeechRecognizerContract.kt
  app/src/main/java/com/aritra/notify/components/biometric/AppBioMetricManager.kt
  app/src/main/java/com/aritra/notify/components/dialog/PermissionDialog.kt
  app/src/main/java/com/aritra/notify/components/dialog/TextDialog.kt
  app/src/main/java/com/aritra/notify/components/note/GridNoteCard.kt
  app/src/main/java/com/aritra/notify/components/note/NoteCard.kt
  app/src/main/java/com/aritra/notify/components/topbar/AddEditTopBar.kt
  app/src/main/java/com/aritra/notify/data/converters/DateTypeConverter.kt
  app/src/main/java/com/aritra/notify/data/converters/UriConverter.kt
  app/src/main/java/com/aritra/notify/data/dao/NoteDao.kt
  app/src/main/java/com/aritra/notify/data/db/NoteDatabase.kt
  app/src/main/java/com/aritra/notify/di/AppModule.kt
  app/src/main/java/com/aritra/notify/domain/models/Note.kt
  app/src/main/java/com/aritra/notify/domain/repository/BackupRepository.kt
  app/src/main/java/com/aritra/notify/domain/repository/NoteRepository.kt
  app/src/main/java/com/aritra/notify/domain/usecase/SaveSelectedImageUseCase.kt
  app/src/main/java/com/aritra/notify/navigation/BottomNavItem.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  app/src/main/java/com/aritra/notify/ui/screens/MainActivity.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreenViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/settingsScreen/SettingsScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/settingsScreen/SettingsViewModel.kt
  app/src/main/java/com/aritra/notify/ui/theme/Color.kt
  app/src/main/java/com/aritra/notify/ui/theme/Theme.kt
  app/src/main/java/com/aritra/notify/ui/theme/Type.kt
  app/src/main/java/com/aritra/notify/utils/CommonExtensions.kt
  app/src/main/java/com/aritra/notify/utils/Const.kt
  app/src/main/java/com/aritra/notify/utils/Context.kt
  app/src/main/java/com/aritra/notify/utils/CsvIo.kt
  app/src/main/java/com/aritra/notify/utils/ShareUtils.kt
  app/src/main/java/com/aritra/notify/utils/Uri.kt
  app/src/main/java/com/aritra/notify/viewmodel/MainViewModel.kt
  app/src/main/java/com/aritra/notify/viewmodel/ThemeViewModel.kt
  app/src/test/java/com/aritra/notify/ExampleUnitTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement, features, ci/cd, hacktoberfest-accepted

#115 Add feat: User can pick multiple image + zoom and pan across image
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/aritra/notify/components/note/GridNoteCard.kt
  app/src/main/java/com/aritra/notify/components/note/NoteCard.kt
  app/src/main/java/com/aritra/notify/data/converters/ListConverter.kt
  app/src/main/java/com/aritra/notify/data/db/NoteDatabase.kt
  app/src/main/java/com/aritra/notify/domain/models/Note.kt
  app/src/main/java/com/aritra/notify/domain/repository/BackupRepository.kt
  app/src/main/java/com/aritra/notify/domain/usecase/SaveSelectedImageUseCase.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement, priority-high, features, important, hacktoberfest-accepted

#120 Feat: multi-selection-deletion-items
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/aritra/notify/components/actions/BackPressHandler.kt
  app/src/main/java/com/aritra/notify/components/note/GridNoteCard.kt
  app/src/main/java/com/aritra/notify/components/note/NoteCard.kt
  app/src/main/java/com/aritra/notify/components/topbar/SelectionModeTopAppBar.kt
  app/src/main/java/com/aritra/notify/data/dao/NoteDao.kt
  app/src/main/java/com/aritra/notify/domain/repository/NoteRepository.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreenViewModel.kt
Labels: priority-medium, features, hacktoberfest-accepted

#123 BugFix - Make input description auto scroll to cursor position when it is out of visible bounds
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/DescriptionTextField.kt
Labels: good first issue, improvement, hacktoberfest-accepted

#136 feature: Secure screen option in settings for enhanced privacy
  app/src/main/java/com/aritra/notify/components/actions/SettingsSwitchCard.kt
  app/src/main/java/com/aritra/notify/di/DataStoreUtil.kt
  app/src/main/java/com/aritra/notify/di/ThemeState.kt
  app/src/main/java/com/aritra/notify/ui/screens/settingsScreen/SettingsScreen.kt
  app/src/main/java/com/aritra/notify/ui/theme/Theme.kt
  app/src/main/java/com/aritra/notify/viewmodel/ThemeViewModel.kt
  app/src/main/res/drawable/phonelink_lock.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, important, improvement, hacktoberfest-accepted

#129 feature: Add sorting options for notes.
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/aritra/notify/components/actions/FilterNotesButton.kt
  app/src/main/java/com/aritra/notify/components/note/NotesFilterDropdown.kt
  app/src/main/java/com/aritra/notify/data/dao/NoteDao.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/utils/NotesFilter.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/utils/NotesFilterExtension.kt
Labels: good first issue, features, hacktoberfest-accepted

#143 Dagger Hilt support KSP
  app/build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: good first issue, improvement, hacktoberfest-accepted

#138 Feature: Attach Photos Captured By Device Camera
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aritra/notify/components/camPreview/CameraPreview.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: good first issue, priority-high, features, hacktoberfest-accepted

#146 Removed Accompanist System UI Controller because of its deprication
  app/build.gradle.kts
Labels: good first issue, dependencies, hacktoberfest-accepted

#150 Word Counter & Avg. Read Time Implementation 📊
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
Labels: enhancement, good first issue, priority-medium, hacktoberfest-accepted

#158 [Feature] self-cleaning
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/aritra/notify/core/DispatcherProvider.kt
  app/src/main/java/com/aritra/notify/core/DispatcherProviderImpl.kt
  app/src/main/java/com/aritra/notify/data/converters/LocalDateTimeConverter.kt
  app/src/main/java/com/aritra/notify/data/dao/NoteDao.kt
  app/src/main/java/com/aritra/notify/data/dao/TrashNoteDao.kt
  app/src/main/java/com/aritra/notify/data/db/NoteDatabase.kt
  app/src/main/java/com/aritra/notify/data/relations/TrashNoteWithNotes.kt
  app/src/main/java/com/aritra/notify/di/AppModule.kt
  app/src/main/java/com/aritra/notify/di/DispatcherModule.kt
  app/src/main/java/com/aritra/notify/di/ViewModelModule.kt
  app/src/main/java/com/aritra/notify/domain/models/Note.kt
  app/src/main/java/com/aritra/notify/domain/models/TrashNote.kt
  app/src/main/java/com/aritra/notify/domain/repository/NoteRepository.kt
  app/src/main/java/com/aritra/notify/domain/repository/trash/TrashNoteRepo.kt
  app/src/main/java/com/aritra/notify/domain/repository/trash/TrashNoteRepoImpl.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyScreens.kt
  app/src/main/java/com/aritra/notify/ui/screens/MainActivity.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreenViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/trash/TrashNoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/trash/TrashNoteState.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/trash/TrashNoteViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/settingsScreen/SettingsScreen.kt
  app/src/main/java/com/aritra/notify/viewmodel/MainViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, priority-high, features, hacktoberfest-accepted

#166 Clickable issues in bottom navigation item
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  gradlew
Labels: good first issue, improvement, hacktoberfest-accepted

#169 Right side navigation button should trigger slide animation from the right side
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  gradlew
Labels: good first issue, improvement, hacktoberfest-accepted

#156 Done: Fix the UX of SearchBar & Bottom Nav Bar
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
Labels: good first issue, features, improvement, hacktoberfest-accepted

#178 change bottomBar to transparent to match the screen color
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
Labels: enhancement, good first issue, ui-fixes, hacktoberfest-accepted

#172 #161 Clickable Animation Issues in Bottom Navigation Item
  .idea/gradle.xml
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
Labels: bug, good first issue, hacktoberfest-accepted

#179 - added text on bottom end for trash note to know remaining how long …
  app/src/main/java/com/aritra/notify/components/note/NoteCard.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/trash/TrashNoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/trash/TrashNoteState.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/trash/TrashNoteViewModel.kt
  app/src/main/res/values/strings.xml
Labels: features, improvement, hacktoberfest-accepted

#185 changes-to-make-textedit-focused-in-case-of-new-note
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/DescriptionTextField.kt
Labels: good first issue, improvement, hacktoberfest-accepted

#189 Removed google-service.json from the codebase
  app/google-services.json
Labels: good first issue, improvement, hacktoberfest-accepted

#190 Feature: Implement the canvas drawing functionality
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/src/main/java/com/aritra/notify/components/topbar/AddEditTopBar.kt
  app/src/main/java/com/aritra/notify/data/dao/NoteDao.kt
  app/src/main/java/com/aritra/notify/domain/models/Note.kt
  app/src/main/java/com/aritra/notify/domain/repository/NoteRepository.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyScreens.kt
  app/src/main/java/com/aritra/notify/ui/screens/drawing/Drawable.kt
  app/src/main/java/com/aritra/notify/ui/screens/drawing/DrawingCanvas.kt
  app/src/main/java/com/aritra/notify/ui/screens/drawing/DrawingScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/drawing/Tool.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/DescriptionTextField.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
  app/src/main/java/com/aritra/notify/utils/DimensionUtils.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: features, hacktoberfest-accepted

#199 chore(add-edit): refactored code
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/aritra/notify/components/appbar/AddEditBottomBar.kt
  app/src/main/java/com/aritra/notify/components/appbar/AddEditTopBar.kt
  app/src/main/java/com/aritra/notify/components/appbar/SelectionModeTopAppBar.kt
  app/src/main/java/com/aritra/notify/components/camPreview/CameraPreview.kt
  app/src/main/java/com/aritra/notify/components/drawing/DrawingScreen.kt
  app/src/main/java/com/aritra/notify/components/topbar/AddEditTopBar.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyApp.kt
  app/src/main/java/com/aritra/notify/navigation/NotifyScreens.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditRoute.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/AddEditViewModel.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/NoteImages.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/addEditScreen/NoteStats.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreen.kt
  app/src/main/java/com/aritra/notify/ui/screens/notes/homeScreen/NoteScreenViewModel.kt
Labels: good first issue, important, optimization, improvement, hacktoberfest-accepted
